version: "3.8"

services:
  azuriom:
    build: .
    # IMPORTANT: do NOT set container_name under Dokploy
    ports:
      - "80" # expose only the container port
    volumes:
      - data:/var/www/html
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - dokploy-network
volumes:
  data:

networks:
  dokploy-network:
    external: true
